"""init

Revision ID: 67d672641718
Revises: 72c348c2830b
Create Date: 2026-08-05 14:48:44.804188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67d672641718'
down_revision: Union[str, None] = '72c348c2830b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_tenders_awarded_submission', 'tenders', 'submissions', ['awarded_vendor_submission_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenders_awarded_submission', 'tenders', type_='foreignkey')
    # ### end Alembic commands ###
