"""purchasing filters offers before the department manager sees them

A bid used to land in front of the department manager the moment a vendor sent
it. It now lands at purchasing first, who decide what is worth putting in front
of the manager: what they forward becomes `forwarded`, what they don't stays
`pending` and the manager never sees it.

Two changes on `offers`:

- a new `forwarded` label on the `offerstatus` enum;
- `forwarded_at` / `forwarded_by`, which is what the manager's view actually
  filters on. A status check wouldn't do - an offer that was forwarded,
  shortlisted and later released has moved past `forwarded` and still has to
  stay visible to the manager.

Hand-written, not autogenerated: alembic does NOT diff enum values. Adding a
member to a Python enum.Enum produces an EMPTY autogenerate migration for that
part, and the failure only shows up at runtime as `invalid input value for
enum`. The columns would have been generated; they are here so the whole change
is one revision.

Revision ID: a3f7c05d81b4
Revises: f1a8d3e70c26
Create Date: 2026-08-18

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'a3f7c05d81b4'
down_revision: Union[str, None] = 'f1a8d3e70c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# offer.py maps the enum without an explicit name= on the status column, so
# SQLAlchemy derived `offerstatus`. `rejected_at_stage` names it explicitly and
# points at the same type, so there is only one to alter here.
ENUM_NAME = "offerstatus"


def upgrade() -> None:
    # Postgres refuses to *use* a new enum value in the same transaction that
    # added it, and the UPDATE below does exactly that. autocommit_block commits
    # the ALTER on its own so the UPDATE can reference the label.
    with op.get_context().autocommit_block():
        op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS 'forwarded'")

    op.add_column("offers", sa.Column("forwarded_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("offers", sa.Column("forwarded_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "offers_forwarded_by_fkey", "offers", "users", ["forwarded_by"], ["id"]
    )

    # Everything already on the table is treated as forwarded, so upgrading an
    # install doesn't silently empty every department manager's screen. Under
    # the old rules these offers were visible to them, and a schema change is
    # not the place to take a decision back.
    #
    # `forwarded_by` stays null: nobody actually made this call, and naming a
    # user who didn't would put a false signature on the record.
    op.execute(
        f"""
        UPDATE offers
           SET forwarded_at = created_at,
               status = CASE WHEN status = 'pending'
                             THEN 'forwarded'::{ENUM_NAME}
                             ELSE status END
         WHERE status <> 'rejected'
        """
    )


def downgrade() -> None:
    # `forwarded` collapses back into `pending`: it is the status those offers
    # held before this revision, and the distinction it carried has nowhere to
    # live once the column is gone.
    op.execute(f"UPDATE offers SET status = 'pending'::{ENUM_NAME} WHERE status = 'forwarded'")

    op.drop_constraint("offers_forwarded_by_fkey", "offers", type_="foreignkey")
    op.drop_column("offers", "forwarded_by")
    op.drop_column("offers", "forwarded_at")

    # A single label can't be dropped from a Postgres enum, so the type is
    # rebuilt without it. Both columns that use it are moved across.
    #
    # `status` carries DEFAULT 'pending'::offerstatus, and Postgres refuses to
    # retype a column whose default is expressed in the type being replaced
    # ("default for column status cannot be cast automatically"). The default
    # comes off first and goes back on afterwards, spelled against the new type.
    op.execute("ALTER TABLE offers ALTER COLUMN status DROP DEFAULT")
    op.execute(f"ALTER TYPE {ENUM_NAME} RENAME TO {ENUM_NAME}_old")
    op.execute(
        f"CREATE TYPE {ENUM_NAME} AS ENUM ('pending', 'selected', 'purchasing_ok', "
        f"'purchasing_manager_ok', 'approved', 'rejected')"
    )
    for column in ("status", "rejected_at_stage"):
        op.execute(
            f"ALTER TABLE offers ALTER COLUMN {column} TYPE {ENUM_NAME} "
            f"USING {column}::text::{ENUM_NAME}"
        )
    op.execute(f"ALTER TABLE offers ALTER COLUMN status SET DEFAULT 'pending'::{ENUM_NAME}")
    op.execute(f"DROP TYPE {ENUM_NAME}_old")
