"""add award_revoked email type and its template

Supply chain can now withdraw an award and hand it to another vendor. The
vendor who loses it needs to be told that specifically — the `loser` template
says they were never selected, which is not what happened.

Hand-written, not autogenerated: alembic does NOT diff enum values. Adding a
member to a Python enum.Enum produces an EMPTY autogenerate migration, and the
failure only shows up at runtime as `invalid input value for enum`.

Revision ID: c4d2a81e6b09
Revises: b8f31d0c5e42
Create Date: 2026-08-11

"""
from typing import Sequence, Union

from alembic import op

revision: str = 'c4d2a81e6b09'
down_revision: Union[str, None] = 'b8f31d0c5e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The type is named `emailtype`, not `email_type` — email.py maps the enum
# without an explicit name=, so SQLAlchemy derived it. Both email_templates.type
# and sent_emails.type use that one type, so there's no duplicate to chase here
# (unlike user_role/userrole, see b8f31d0c5e42).
ENUM_NAME = "emailtype"

SUBJECT = "Award Withdrawn - {tender_serial}"
BODY = (
    "Dear {vendor_contact},\n\n"
    "We are writing regarding {tender_name} ({tender_serial}), which was "
    "previously awarded to {vendor_company}.\n\n"
    "That award has been withdrawn and the tender reassigned to another "
    "vendor. Our procurement team will be in touch about the reasons and "
    "any next steps.\n\n"
    "Your Bid: {currency} {bid_amount}\n\n"
    "We value your participation and encourage you to bid on future tenders.\n\n"
    "Best regards,\nTenderFlow Procurement Team"
)


def upgrade() -> None:
    # Postgres refuses to *use* a new enum value in the same transaction that
    # added it, and the INSERT below does exactly that. autocommit_block commits
    # the ALTER on its own so the INSERT can reference the label.
    with op.get_context().autocommit_block():
        op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS 'award_revoked'")

    # Matches DEFAULT_TEMPLATES in seed.py, so an upgraded database and a freshly
    # seeded one produce the same wording. ON CONFLICT leaves any edit alone.
    op.execute(
        f"""
        INSERT INTO email_templates (type, subject, body)
        VALUES ('award_revoked', {_q(SUBJECT)}, {_q(BODY)})
        ON CONFLICT (type) DO NOTHING
        """
    )


def downgrade() -> None:
    # A single label can't be dropped from a Postgres enum, so the type is
    # rebuilt without it. Rows carrying the label have to go first — for
    # sent_emails that means deleting the notifications themselves, since the
    # column is NOT NULL and no other type honestly describes them.
    op.execute("DELETE FROM email_templates WHERE type = 'award_revoked'")
    op.execute("DELETE FROM sent_emails WHERE type = 'award_revoked'")

    op.execute(f"ALTER TYPE {ENUM_NAME} RENAME TO {ENUM_NAME}_old")
    op.execute(f"CREATE TYPE {ENUM_NAME} AS ENUM ('winner', 'loser')")
    for table in ("email_templates", "sent_emails"):
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN type TYPE {ENUM_NAME} "
            f"USING type::text::{ENUM_NAME}"
        )
    op.execute(f"DROP TYPE {ENUM_NAME}_old")


def _q(value: str) -> str:
    """Single-quoted SQL literal with embedded quotes doubled."""
    escaped = value.replace("'", "''")
    return f"'{escaped}'"
